### ISSUE TITLE
Change SE to SD in alien

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#80] opened 2015-10-26 16:25 UTC
I will send a new files with SD instead of SE for traits, it should be easier to understand for the user.

**Comment by paternogbc** [comment] 2015-10-26 16:29
great!

**Comment by caterinap** [comment] 2015-10-26 18:09
Here it is!
I am not sure how to add it, I also changed the gather_alienMammals.R file accordingly.
[alienMammals.txt](https://github.com/paternogbc/sensiPhy/files/21107/alienMammals.txt)

**Comment by paternogbc** [comment] 2015-10-26 19:01
Hi Cat,

did you uploaded the file to raw-data or is just sending it by this issue?
The name of the columns should be trait_SD, right?

In the gather_alienMammals.R stills trait_SE. Did you push all ready?

I can include as a dataset because you need to transform this files into .rda file before.
cheers,
G

**Comment by caterinap** [comment] 2015-10-26 19:29
Hey,
The right file is the one I attached to the previous issue. I did not push it to the repository because I was not sure how it had to be done :)
The column names are SD in both the file and gather_alienMammals.R.
All my changes are in the branch SensiPhyCat.

cheers,

**Comment by paternogbc** [comment] 2015-10-26 19:31
Nice ;)

When you push these changes I will update our Alien dataset, then.
Because It will prevent problems. You can also commit only these changes if you are working in other files and they are not ready yet. 

All the best,
G

**Comment by caterinap** [comment] 2015-10-26 19:39
Mmmmh, I committed all the changes to the branch already... do you want to merge then?

**Comment by paternogbc** [comment] 2015-10-26 19:44
if the changes are ready, we can merge! Your call =)

**Comment by paternogbc** [comment] 2015-10-26 20:08
There are some problems with the merge, so automatic merge is not possible. 
Are you still working on this branch?

Otherwise I will fix the issues and perform a manual merge.

Thanks for the fixes =)
Bets,
Guga

**Comment by caterinap** [comment] 2015-10-26 20:18
Yep, I am done for now. I just need to add the examples to phyglm functions once we have chosen the other variables, but it will be later.
My devtools check did not give any issue.. is it the ggplot problem?

thank you!!
bjs

**Comment by paternogbc** [comment] 2015-10-26 20:22
Ok no problem.

The issues are not with CRAN check (this is because ggplot2 dev version). I was talking about the merge.  Sometimes you can merge without any manual checking. But probably I made some changes in the files you also worked and then you can not merge directely, you need manual checking. =)
So I will do this and merge. After that you can pull everything then start working on other files.

best,
G

**Comment by caterinap** [comment] 2015-10-26 20:40
oh I see, sorry, did not get it!!!

thanks!!!

**Comment by paternogbc** [comment] 2015-10-26 20:40
Hi Cat!

everything merged =) no errors. 
So before working again.. we need to Pull all changes ;)

cheers,
G

**Comment by caterinap** [comment] 2015-10-26 20:45
Sure! I think these were changes that were on the branch since last time, so when I pulled from "master" I did not get them. thanks!
 good night :)

**Comment by paternogbc** [comment] 2015-10-27 11:59
Hi Cat,

did you included the 95_CI in tree_ and intra_ stat output?

I will wait for that to match with plot.tree.intra, so I can use the same value produced in the original function to plot confidence interval regression lines. 

If you want I can do this =)
G

**Comment by caterinap** [comment] 2015-10-27 12:42
hi,
Yes the upper and lower (2.5%) and upper (97.5%) confidence limits for the slope are given in the summary: IC.slope025,IC.slope975. Maybe "CI" instead of "IC" would be better :).
I used the stats::confint function to extract them.

**Comment by paternogbc** [comment] 2015-10-27 12:45
That is very strange because I can not find this in the original function: https://github.com/paternogbc/sensiPhy/blob/master/R/tree_phylolm.R

Maybe when I merged we lost some changes!!! ;(( 
At least I have lost some early commits! 

I will check on your original branch! dam! kkk

**Comment by caterinap** [comment] 2015-10-27 12:50
Mmmh.. I can see them on both: 
https://github.com/paternogbc/sensiPhy/blob/master/R/intra_phylolm.R (lines 103, 150, 165)
https://github.com/paternogbc/sensiPhy/blob/master/R/tree_phylolm.R (lines 76, 106, 119)

**Comment by paternogbc** [comment] 2015-10-27 12:56
Yeah.. you are right but they are not in the summary.stats. The confidence interval of the slopes, generated from the distribution of slopes (in the same way we present SD of the slopes, and mean, I think we could also present the IC for this distribution. And this could be ploted instead of the standard error). In this line of code:

  statresults<-data.frame(min=apply(intra.model.estimates,2,min),
                          max=apply(intra.model.estimates,2,max),
                          mean=apply(intra.model.estimates,2,mean),
                          sd_intra=apply(mean_by_randomval,2,stats::sd))[-1,]

Do you agree?

Sorry if I am confusing..kk

**Comment by caterinap** [comment] 2015-10-27 13:05
Ok, got it! I am going to add it. Should we keep the other CI or it is too confusing ?

**Comment by paternogbc** [comment] 2015-10-27 13:11
I would remove to avoid confusion. 

The code to calculate the error based on the t distribution is:

error <- qt(0.975, df = n-1) * s / sqrt(n)

where in our functions, n = times; s  = sd_intra or sd_tree

I gues we can simple add two lines 
in statresults after the line:
sd_intra=apply(mean_by_randomval,2,stats::sd))[-1,] ,
 
    CI_low = mean - qt(0.975, df = times-1) * sd_intra / sqrt(times) 
    CI_high = mean + qt(0.975, df = times-1) * sd_intra / sqrt(times)

This will give the confidence interval correcting by the number if simulations (t-distribution approachs 1.96 when times = 30, but is bigger for times < 30).

Do you think this is correct?
cheers,
G

**Comment by paternogbc** [comment] 2015-10-27 13:14
atually I am not sure it will work because the variables 'mean' and 'sd_intra' are both created inside the same command. I know this works with dplyr, but will not work with our function. So we need to create the variables first, then integrate them in the data.frame...

**Comment by caterinap** [comment] 2015-10-27 13:30
Or add two lines after statresults like that:

`statresults$CI_low<-statresults$mean - qnorm(0.975) * statresults$sd_intra / sqrt(nrow(model_results))
statresults$CI_high<-statresults$mean + qnorm(0.975) * statresults$sd_intra / sqrt(nrow(model_results))`
I would use nrows in case some models do not converge. In a previous script I used qnorm but I think qt is ok too.
What do you think?

**Comment by paternogbc** [comment] 2015-10-27 13:34
great idea, much easier! 

I would stick with qt(0.975, df = times-1) because it is more conservative when the number of trees or simulations are below. I would also use 'times' instead of nrow(model_results) for simplicity.

cheers,
Guga

**Comment by caterinap** [comment] 2015-10-27 13:38
ok, great ! (and sorry for the messy inline code)
just to avoid problems I think it is better not working at the same time, let me know when you are done (or I can do it early in the European morning)

cheers

**Comment by paternogbc** [comment] 2015-10-27 13:43
Hey Cat! I have finished changing files. You can go for it ;)
remember to PULL because I have made some changes. Also, check if you are not working on the sensiCat branch. This might cause problems and I have done this without noticing. 

We can delete sensiCat branch now because we have merged. If you think you going to do big changes it might be better to start a new branch from master. 

See what you think is best.

Cheers,
G

**Comment by caterinap** [comment] 2015-10-27 13:48
Don't worry I always pull before starting any change ;) My main error was to work again on that stupid old branch... sorry.. I am just doing minor changes so I am going to stay on master. And yes, better delete SensiPhyCat..

Cheers!

**Comment by caterinap** [comment] 2015-10-27 14:26
done :-) (in functions and plot)

**Comment by paternogbc** [comment] 2015-10-27 14:30
great! =))

**Closed** 2015-11-24 18:22 UTC
Labels: To do list!
