### ISSUE TITLE
Transformations standardisation

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#133] opened 2017-05-08 15:09 UTC
Standardising how the transformations work turned out to actually be really complex (at least for me!). The reason is that it works very differently in the intra loops (where we apply the transformation to the whole vector of the recreated dataset) and influ (where we essentially apply it to the formula directly. This is problematic in the intra_influ interaction because there we essentially need to do both. 

I have now solved this in a really ugly way, where the user supplies the transformation as a character string `x.transf = 'log'`. For the formula we then apply it using a bunch of pastes, and for the the loops we turn it back into a function with do.call. 

In principle this works fine, and we could use it to standardise throughout, but it has two main disadvantages: (1) it's really ugly and (2) it doesn't allow for any more complex transformation (log x + 25), that people could well want to use. 

Let's think about this more, but not prioritise as I don't think it's critical for this resubmission.

**Comment by diogoprov** [comment] 2017-07-13 13:39
I'm having an issue with `intra_phylm`. My model is an "ANCOVA", with a categorical predictor and a continuous one as predictors and a continuous response variable (the distance jumped by frog species), of the type:

```
intra <- intra_phylm(mean_distance~microhabitat+SVL, phy = filo_jes, track = F, 
                      data = vazia_aprox, Vy = "se_distance",
                      times = 100, x.transf = NULL, y.transf = NULL)
```
So, I need to transform neither the predictor (doesn't make sense) nor the response.
However, I kepp getting this error asking for me to include x.transf and y.transf. But even when I include them as `NULL` or leave if with `log` the error below still appears:

```
Error in intra_phylm(mean_distance ~ microhabitat + SVL, phy = filo_jes,  : 
  Please use arguments y.transf or x.transf for data transformation
```
Any ideas? I'm using v. 0.6.999999 in R 3.4.0.

**Comment by paternogbc** [comment] 2017-07-13 13:51
Dear @diogoprov ,

Thanks for you contact.
The reason why you are getting this error is because this function was developed to perform sensitivity analysis only for linear regressions (y and x continuous), but not ANCOVA or more complex models. We are working on a general method to perform sensitivity analysis for all sorts of complex models involving categorical and continuous variables as predictors. But this take some time before it is available. 
At the moment, I have some initial ideas for running sensitivity analysis of ANCOVA models. If you can wait around 2 weeks I can provide you the code. At the moment we are working on other issues since a manuscript describing the package is under review. 

all the best

**Comment by diogoprov** [comment] 2017-07-13 14:10
Sure I can wait @paternogbc, no problem! Thanks for quick reply. BTW, I've been teaching a course on comparative phylo methods and when I taught PGLS I mention your package and we make a little practice. I'm glad the package is finally on CRAN and is getting the recognition it deserves by being published. Congrats for the great work!

**Comment by paternogbc** [comment] 2017-07-17 09:24
Hi @diogoprov, thanks for you comments! 
it is really great to hear that the package is being used in a course on PCM! Also, we would be very happy to receive any feedback based on your experience using sensiPhy. 
Please feel free to open issues and suggest new ideas for the package. 
sensiPhy v0.7 is schedule to be released on mid August and will include sensitivity analysis for phylogenetic signal estimates and other features. 
We keep in touch. All the best!

**Comment by paternogbc** [comment] 2017-08-18 22:45
Hey @diogoprov, I am closing this issue but will get in contact with you by e-mail.

**Closed by paternogbc** 2017-08-18 22:45 UTC
Labels: enhancement
